'use client'
import './globals.css'
import { Next13ProgressBar } from 'next13-progressbar';




 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  dir='rtl'>
      <Next13ProgressBar height="2px" color="#C0392B" options={{ showSpinner: true }} showOnShallow />
        {children}
        
      </body>
    </html>
  )
}
