const citySearch = [
    { id: 1, name: 'تهران' },
    { id: 2, name: 'مشهد' },
    { id: 3, name: 'بجنورد' },
    { id: 4, name: 'آمل' },
    { id: 5, name: 'رشت' },
    { id: 6, name: 'کرمان' },
    { id: 7, name: 'شهریار' },
    { id: 8, name: 'قم' },
    { id: 9, name: 'اندیمشک' },
    { id: 10, name: 'بومهن' },
    { id: 12, name: 'رودهن' },
    { id: 13, name: 'دماوند' },
    { id: 14, name: 'گرگان' },
    { id: 15, name: 'بابل' },
    { id: 16, name: 'رامسر' },
    { id: 17, name: 'نکا' },
    { id: 18, name: 'بهشهر' },
    { id: 19, name: 'اصفهان' },
    { id: 20, name: 'یزد' },
    { id: 21, name: 'کرج' },
]